BootStrap: docker
From: continuumio/miniconda:latest
IncludeCmd: yes


%post
    umask 0022
    apt update
    apt -y dist-upgrade
    apt -y install git wget rsync pigz

    export PATH=/opt/conda/bin:$PATH
    mkdir -p /scratch
    mkdir -p /gpfs
    mkdir -p sw

    conda install --yes                 \
      -c conda-forge                    \
      -c bioconda                       \
      -c r                              \
      -c defaults                       \
      -c anaconda                       \
      -c biobuilds                      \
      -c esri                           \
      bedtools=2.27.1                   \
      biopython                         \
      bwa=0.7.15                        \
      picard                            \
      fastqc                            \
      cutadapt                          \
      samtools=1.7                      \
      python=3.7                        \
      pysam=0.14                        \
      pybedtools=0.8.0                  \
      statsmodels=0.9.0                 \
      r=3.5.1                           \
      r-devtools                        \
      r-ggplot2=3.1.0                   \
      r-ggrepel=0.8.0                   \
      r-dplyr                           \
      r-tidyr=0.8.2                     \
      r-viridis                         \
      r-rcolorbrewer                    \
      bioconductor-genomicranges=1.34.0 \
      r-optparse=1.6.0                  \
      r-glue=1.3.0                      \
      r-MASS=7.3-50                     \
      sra-tools=2.8.1                   \
      fastx-toolkit=0.0.14              \
      ataqv

    conda clean --all

    cd /sw && git clone https://github.com/ParkerLab/cta && cd cta && \
      make install prefix=/usr/local && cd ..


%environment
    unset CONDA_DEFAULT_ENV
    export PICARD_JAR=$(find /opt/conda/share | grep picard.jar)
    export PATH=/opt/conda/bin:$PATH


%labels
    Author porchard@umich.edu
    Version v0.0.1
