BootStrap: docker
From: continuumio/miniconda3:latest
IncludeCmd: yes

%post
    umask 0022
    apt-get -qq update && apt-get -qq -y dist-upgrade

    export PATH=/opt/conda/bin:$PATH

    mkdir -p /sw
    mkdir -p /scratch
    mkdir -p /gpfs

    conda config --set safety_checks disabled

    conda install --yes          \
      -c conda-forge             \
      -c bioconda                \
      python=3.7                 \
      r-base=3.6                 \
      r-essentials               \
      bedtools >=2.27            \
      bamutil=1.0                \
      bioconductor-garfield      \
      bioconductor-genomicranges \
      deeptools                  \
      demuxlet=1.0               \
      fastx_toolkit              \
      fastqc >=0.10              \
      fgwas=0.3.6                \
      pysam >=0.15               \
      biopython                  \
      pybedtools                 \
      r-devtools                 \
      r-optparse                 \
      r-glue                     \
      r-ggseqlogo                \
      sra-tools >=2.10           \
      subread >=1.6.4            \
      samtools >=1.9             \
      ucsc-bedclip=377           \
      ucsc-bedsort=377

    conda clean --all


%environment
    unset CONDA_DEFAULT_ENV
    export ANACONDA_HOME=/opt/conda
    export LC_ALL=C

%labels
    Author vivekrai@umich.edu
    Version v0.0.1
