BootStrap: docker
From: continuumio/miniconda3:latest
IncludeCmd: yes

%post
    umask 0022
    apt-get -qq update && apt-get -qq -y upgrade

    export PATH=/opt/conda/bin:$PATH

    mkdir -p /sw
    mkdir -p /scratch
    mkdir -p /gpfs

    conda config --set safety_checks disabled
    conda install -c conda-forge mamba

    mamba install -y             \
      -c conda-forge \
      -c bioconda \
      -c defaults \
      python>=3.7 \
      r-base>=3.6             \
      snakemake \
      nextflow \
      r-essentials>=3.6               \
      r-devtools                 \
      r-optparse>=1.6.2            \
      r-glue \
      bedtools>=2.27.1           \
      fastqc>=0.10 \
      bamutil=1.0.* \
      biopython \
      deeptools  \
      pybedtools \
      fastx_toolkit>=0.0.14              \
      pysam>=0.15 \
      sra-tools>=2.8.1 \
      samtools>=1.9  \
      plink>=1.8 \
      bcftools>=1.8 \
      bioconductor-genomicranges=1.34   \
      ucsc-bedsort=377 \
      ucsc-bedclip=377 

    mamba clean --all


%environment
    unset CONDA_DEFAULT_ENV
    export ANACONDA_HOME=/opt/conda
    export LC_ALL=C

%labels
    Author vivekrai@umich.edu
    Version v0.0.2
